//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ex1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Data
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Data()
        {
            this.Disable = false;
        }
    
        public long ID { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Patronymic { get; set; }
        public string Phonenumber { get; set; }
        public System.DateTime DateBirth { get; set; }
        public string Email { get; set; }
        public bool Disable { get; set; }
        public Nullable<System.DateTime> DisableDate { get; set; }
        public string DisableAuthor { get; set; }
    }
}
